## NumPy

NumPy is a Linear Algebra Library for Python, the reason it is important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

NumPy is also incredibly fast, as it has bindings to C libraries. 

In [1]:
import numpy as np

## Numpy Arrays

Numpy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and metrices. Vetctors are strictly 1 -d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

In [2]:
my_list = [0,1,2]

In [3]:
my_list

[0, 1, 2]

In [5]:
np.array(my_list)

array([0, 1, 2])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

### arange

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones(3)

array([1., 1., 1.])

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace

Return evenly spaced numbers over a specified interval.

In [20]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### eye
Create an identity matrix

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random

### rand
Create an array of the given shape and populate it with random samples from a uniform distribution over 0,1.

In [23]:
np.random.rand(2)

array([0.07523344, 0.96003744])

In [24]:
np.random.rand(5,5)

array([[0.6267995 , 0.63615937, 0.29534991, 0.21483733, 0.79163976],
       [0.47765262, 0.85620657, 0.03546628, 0.59084659, 0.27275628],
       [0.12491524, 0.42694768, 0.81361693, 0.64649507, 0.96477696],
       [0.29502602, 0.24885957, 0.24271121, 0.30956679, 0.46481888],
       [0.97905534, 0.0217572 , 0.21220273, 0.97675182, 0.63602515]])

### randn

In [26]:
np.random.randn(2)

array([-1.0222422 ,  0.72064171])

In [27]:
np.random.randn(5,5)

array([[ 0.63245253, -0.90772046, -0.55208108,  0.18114809, -0.86713177],
       [ 1.15964762, -0.88499065, -0.64152058,  1.7891193 ,  1.1711555 ],
       [-1.74682079, -0.75400732,  0.74124595, -0.24202469, -0.575986  ],
       [ 2.29536729, -0.94241256, -0.30614514,  0.47059893,  0.65636003],
       [-1.37430797,  0.08578523,  1.28639324,  0.35039678,  0.45443569]])

### randint

In [29]:
np.random.randint(1,100)

92

In [30]:
np.random.randint(1,100,10)

array([46,  4, 12, 88, 58,  7, 30, 30, 21, 97])

## Array Attributes and Methods

In [32]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr

array([14, 31,  0, 24,  8, 47,  0, 10, 37, 20])

## Reshape

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax,argmin

In [36]:
ranarr

array([14, 31,  0, 24,  8, 47,  0, 10, 37, 20])

In [37]:
ranarr.max()

47

In [38]:
ranarr.min()

0

In [40]:
ranarr.argmax()

5

In [42]:
ranarr.argmin()

2

## Shape

In [43]:
#vector 
arr.shape

(25,)

In [44]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [45]:
arr.reshape(1,25).shape

(1, 25)

In [46]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [47]:
arr.reshape(25,1).shape

(25, 1)

## dtype

In [48]:
arr.dtype

dtype('int32')